# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Smartnova: VIS Research Group"
subtitle: "Data Visualization and Visual Analytics System Research"
email: "wakita at is titech ac jp"
name: "Smartnova: VIS Research Group"
description: >- # this means to ignore newlines until "baseurl:"
  Smartnova: Data Visualization and Visual Analytics System Research Group

url: "https://wakita.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/smartnova" # the subpath of your site, e.g. /blog
repository: "wakita/smartnova"

author:
  name: "脇田 建 / Ken Wakita"
  avatar: /assets/images/Ken_Wakita.jpg
  bio: "数理・計算科学系 情報理工学院 東京工業大学 / School of Computing, Tokyo Institute of Technology"
  location: "Tokyo, Japan"
  links:
    - label: "Contact"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:wakita@is.titech.ac.jp"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wakita"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kwakita"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/ken.wakita"

twitter:
  username: kwakita
facebook:
  username: ken.wakita
github: [metadata]

# theme
minimal_mistakes_skin: "air"
teaser: /assets/images/supernova.jpg
logo: /assets/images/Ken_Wakita.jpg

  #locale: "ja"

plugins:
  - jekyll-feed
  - jekyll-include-cache

    #collections_dir: _collections

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      share: true
      related: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wakita"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/ken.wakita/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kwakita"

include:
  - pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - Readme.md
  - bin/
  - etc/
  - notes
  - work/

encoding: "utf-8"
# Theme settings
# remote_theme: "mmistakes/jekyll-theme-basically-basic"
# remote_theme: "mmistakes/minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
